# Generated by Django 3.1.7 on 2021-08-16 04:44

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('staf_n', models.CharField(max_length=100, verbose_name=backend.models.staf)),
                ('state', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Present', max_length=100)),
                ('date', models.CharField(default='August 16, 2021', editable=False, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=1000)),
                ('category', models.CharField(default='', max_length=1000, verbose_name=backend.models.category)),
                ('Sale_price', models.IntegerField(default='')),
                ('Buy_price', models.IntegerField(default='')),
                ('stock', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='staf',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
