# Generated by Django 3.1.7 on 2021-08-16 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='staf_n',
            new_name='staf_name',
        ),
    ]
