# Generated by Django 3.1.7 on 2021-08-16 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210816_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='staf_name',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='backend.staf'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default='', max_length=1000, on_delete=django.db.models.deletion.CASCADE, to='backend.category'),
        ),
    ]
