# Generated by Django 3.1.7 on 2021-08-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210816_1020'),
    ]

    operations = [
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_add', models.CharField(default='August 16, 2021', max_length=1000)),
                ('note_body', models.TextField(default='', max_length=10000)),
            ],
        ),
    ]
