# Generated by Django 3.1.7 on 2021-08-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210817_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=200)),
                ('contact', models.CharField(default='', max_length=30)),
                ('gst_no', models.CharField(default='', max_length=100)),
                ('badge', models.CharField(max_length=200)),
            ],
        ),
    ]
