# Generated by Django 3.1.7 on 2021-08-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210818_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='state',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='None', max_length=100),
        ),
    ]
