# Generated by Django 3.1.7 on 2021-08-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210818_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order_date',
            field=models.CharField(default='August 18, 202113:14:42', max_length=1000),
        ),
    ]
