# Generated by Django 3.1.7 on 2021-08-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_invoice_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_date',
            field=models.CharField(default='August 18, 202114:09:11', max_length=1000),
        ),
    ]
