# Generated by Django 3.1.7 on 2021-08-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20210818_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_date',
            field=models.CharField(default='August 18, 202114:10:51', max_length=1000),
        ),
    ]
