# Generated by Django 3.1.7 on 2021-08-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20210818_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='inv_type',
            field=models.CharField(default='Normal_Invoice', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_date',
            field=models.CharField(default='August 18, 202114:37:49', max_length=1000),
        ),
    ]
