# Generated by Django 3.1.7 on 2021-08-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20210818_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_date',
            field=models.CharField(default='August 18, 202122:32:39', max_length=1000),
        ),
    ]
