# Generated by Django 3.1.7 on 2021-08-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20210818_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_date',
            field=models.CharField(default='August 18, 202122:53:34', max_length=1000),
        ),
    ]
