# Generated by Django 3.1.7 on 2021-08-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210818_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.CharField(default='August 19, 2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_date',
            field=models.CharField(default='August 19, 202107:47:18', max_length=1000),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date_add',
            field=models.CharField(default='August 19, 2021', max_length=1000),
        ),
    ]
