# Generated by Django 3.1.7 on 2021-08-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_auto_20210819_0748'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellhistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(default='August 19, 202108:01:13', max_length=1000)),
                ('detail', models.CharField(default='Product', max_length=100)),
                ('total', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_date',
            field=models.CharField(default='August 19, 202108:01:13', max_length=1000),
        ),
    ]
