# Generated by Django 3.1.7 on 2021-08-19 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0044_auto_20210819_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_date',
            field=models.CharField(default='August 19, 202123:18:54', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='date',
            field=models.CharField(default='August 19, 202123:18:54', max_length=1000),
        ),
    ]
