# Generated by Django 3.1.7 on 2021-08-20 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_auto_20210819_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='date',
            field=models.CharField(default='August 20, 2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_date',
            field=models.CharField(default='August 20, 202111:08:22', max_length=1000),
        ),
        migrations.AlterField(
            model_name='notes',
            name='date_add',
            field=models.CharField(default='August 20, 2021', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='date',
            field=models.CharField(default='August 20, 202111:08:22', max_length=1000),
        ),
        migrations.CreateModel(
            name='paymenthistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pay', models.CharField(default='', max_length=100)),
                ('staf_name', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='backend.staf')),
            ],
        ),
    ]
