# Generated by Django 3.1.7 on 2021-08-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_auto_20210820_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='pay_date',
            field=models.CharField(default='August 20, 202111:13:05', max_length=1000),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_date',
            field=models.CharField(default='August 20, 202111:13:05', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='date',
            field=models.CharField(default='August 20, 202111:13:05', max_length=1000),
        ),
    ]
