# Generated by Django 3.1.7 on 2021-08-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_auto_20210820_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_date',
            field=models.CharField(default='August 20, 202112:32:39', max_length=1000),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='pay_date',
            field=models.CharField(default='August 20, 202112:32:39', max_length=1000),
        ),
        migrations.AlterField(
            model_name='products',
            name='month',
            field=models.CharField(default='August', max_length=100),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='date',
            field=models.CharField(default='August 20, 202112:32:39', max_length=1000),
        ),
    ]
