# Generated by Django 3.1.7 on 2021-08-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_auto_20210820_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_date',
            field=models.CharField(default='August 20, 202115:36:30', max_length=1000),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='pay_date',
            field=models.CharField(default='August 20, 202115:36:30', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='date',
            field=models.CharField(default='August 20, 202115:36:30', max_length=1000),
        ),
    ]
