# Generated by Django 3.1.7 on 2021-08-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_auto_20210820_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='order_date',
            field=models.CharField(default='August 20, 202115:56:04', max_length=1000),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='pay_date',
            field=models.CharField(default='August 20, 202115:56:04', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sellhistory',
            name='date',
            field=models.CharField(default='August 20, 202115:56:04', max_length=1000),
        ),
    ]
